<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE rezept [
  <!ELEMENT rezept (rezeptname,untertitel?,bilder,zutaten,zubereitung)+>
  <!ELEMENT bilder (bild)*>
  <!ELEMENT zutaten (portionen,(zutat)+)>
  <!ELEMENT zubereitung (arbeitszeit,schwierigkeitsgrad,brennwert,arbeitsschritte)>
  <!ELEMENT zutat (menge,zutatname)>
  <!ELEMENT bild (url,beschreibung)>
  
  <!ELEMENT rezeptname (#PCDATA)>
  <!ELEMENT untertitel (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  <!ELEMENT portionen (#PCDATA)>
  <!ELEMENT beschreibung (#PCDATA)>
  <!ELEMENT menge (#PCDATA)>
  <!ELEMENT zutatname (#PCDATA)>
  <!ELEMENT arbeitszeit (#PCDATA)>
  <!ELEMENT schwierigkeitsgrad (#PCDATA)>
  <!ELEMENT brennwert (#PCDATA)>
  <!ELEMENT arbeitsschritte (#PCDATA)> 
]>

<rezept>

	<rezeptname>Lenchen’s Schokoladenkuchen</rezeptname>
	
	<bilder>
		<bild>
			<url>lenchen_s_schokoladenkuchen.jpg</url> 
			<beschreibung>1/60: Foto von Ben</beschreibung>
		</bild>
		<bild>
			<url>kuchen2.jpg</url> 
			<beschreibung>2/60: Foto von Dennis</beschreibung>
		</bild>
	</bilder>
	
	<zutaten>
		<portionen>16 </portionen>
		<zutat> <menge>200g</menge> 	<zutatname>Butter</zutatname> </zutat>
		<zutat> <menge>200g</menge> 	<zutatname>Zucker</zutatname> </zutat>
		<zutat> <menge>200g</menge> 	<zutatname>Schokolade,Blockschokolade</zutatname> </zutat>
		<zutat> <menge>120g</menge> 	<zutatname>Mehl</zutatname> </zutat>
		<zutat> <menge>1/2 TL</menge> 	<zutatname>Backpulver</zutatname> </zutat>
		<zutat> <menge>1 Pkt.</menge> 	<zutatname>Vanillezucker</zutatname> </zutat>
		<zutat> <menge>4</menge> 	<zutatname>Eier</zutatname> </zutat>
	</zutaten>
	
	<zubereitung>
		<arbeitszeit> ca 1 Std. </arbeitszeit>
		<schwierigkeitsgrad> normal </schwierigkeitsgrad>
		<brennwert> 295 kcal </brennwert>
		<arbeitsschritte> Butter und Schokolade im Wasserbad schmelzen. Eier trennen. Eiweiß steif schlagen. 
		Eigelbe, Zucker und Vanillezucker verrühren. Geschmolzene Butter-Schokomasse hinzufügen und mischen. 
		Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben. 
		In eine gut gefettete Form geben. 
		Bei 180°Grad 40 – 50 Minuten backen. </arbeitsschritte>
	</zubereitung>
	
</rezept>
