=== BenWur/wba2/Phase2/XSD/Post.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Schema für Posts (nur für Admins) in Event -->

 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--Vollstaendige Postdaten -->

 <xs:element name="post">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="eventType"/>
       <!-- Dauer des Events, automatisch übergeben. Z.B. Fussball 110Min -->
        <xs:element type="xs:duration" name="eventDuration"/>
        <xs:element ref="postAut">
        </xs:element>
        <xs:element name="postContent" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
            <!-- postContent wird immer mit zeit angegeben. Von eventDuration übergeben -->
              <xs:element name="postTime">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:duration">
                      <xs:attribute type="xs:string" name="unit" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element ref="postElement"/>
              <xs:element ref="postText"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
     <!-- userID + eventID, klare Identifizierung des Events bzw. Posts-->
      <xs:attribute type="xs:byte" name="userID"/>
      <xs:attribute type="xs:byte" name="eventID"/>
    </xs:complexType>
  </xs:element>
  
  <!-- Username -->
   <xs:element name="username">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="3"/>
				<xs:maxLength value="15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

   <!-- Typ des Events bestimmen auto. übergeben durch eventID -> wichtig fuer postElements -->
	<xs:element name="eventType" default="">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=""/>
				<xs:enumeration value="Football"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
  <!-- Admin des Events, sollte automatisch übergeben werden. Max u. min 1 Admin pro Event -->
   <xs:element name="postAut">
		<xs:complexType>
            <xs:sequence>
              <xs:element ref="username" maxOccurs="1" minOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>	
        
   <!-- durch eventType bestimmte Elemente für postContent -->
	<xs:element name="postElement" default="">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=""/>
				<xs:enumeration value="Goal"/>
				<xs:enumeration value="Red Card"/>
				<xs:enumeration value="Yellow Card"/>
				<xs:enumeration value="Corner"/>
				<xs:enumeration value="Penalty"/>
				<xs:enumeration value="Foul"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<!-- Ereignisse im Event, Admin only -->
   <xs:element name="postText">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="2"/>
				<xs:maxLength value="70"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
</xs:schema>

=== BenWur/wba2/Phase2/XML/Post.xml
<?xml version="1.0" encoding="UTF-8"?>

<post
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../XSD/Post.xsd"
	userID="26" eventID="109">
	
	<eventType>Football</eventType>
	<eventDuration>PT110M</eventDuration>
	<postAut>
		<username>Holly998</username>
	</postAut>
	<postContent>
		<postTime unit="Min.">PT63M</postTime>
		<postElement>Goal</postElement>
		<postText>Great shot of E. Cavani and it's the 1-0 for Napoli!!</postText>
	</postContent>
	<postContent>
		<postTime unit="Min.">PT55M</postTime>
		<postElement>Yellow Card</postElement>
		<postText>Terrible foul from behind against Robben, deserved Yellow Card!</postText>
	</postContent>
	<postContent>
		<postTime unit="Min.">PT49M</postTime>
		<postElement>Corner</postElement>
		<postText>Another corner for Bayern, this time without consequences.</postText>
	</postContent>
	
</post>
